# Generated by Django 5.0 on 2023-12-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=32)),
                (
                    "currency_type",
                    models.CharField(
                        choices=[("Crypto", "CRYPTO"), ("FIAT", "FIAT")], max_length=16
                    ),
                ),
                ("decimals", models.IntegerField(default=2)),
            ],
            options={
                "verbose_name_plural": "Currencies",
            },
        ),
    ]
