# Generated by Django 5.0 on 2023-12-19 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Asset", "ASSET"),
                            ("Liabilities", "LIABILITIES"),
                            ("Equity", "EQUITY"),
                            ("Revenue", "REVENUE"),
                            ("Receivable", "RECEIVABLE"),
                            ("Payable", "PAYABLE"),
                            ("Expenses", "EXPENSES"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.currency"
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.entity"
                    ),
                ),
            ],
        ),
    ]
